-- Sole schema authority. Run with migration credentials, never the API role.
create extension if not exists pgcrypto;
create schema if not exists app;
create table app.profiles (
 id uuid primary key, email text not null, name text not null default '',
 disabled boolean not null default false, created_at timestamptz not null default now()
);
create table app.staff_members (
 user_id uuid primary key references app.profiles(id),
 role text not null check(role in ('super_admin','admin','editor','order_manager')),
 active boolean not null default true
);
create table app.sessions (
 id_hash text primary key, user_id uuid not null references app.profiles(id),
 encrypted_tokens text not null, csrf text not null,
 expires_at timestamptz not null, created_at timestamptz not null default now(),
 refreshed_at timestamptz not null default now()
);
create index on app.sessions(user_id);
create table app.oauth_states (
 id_hash text primary key, verifier text not null, expires_at timestamptz not null
);
create table app.categories (
 id bigint generated by default as identity primary key, slug text unique not null,
 name_ko text not null, name_en text not null, is_active boolean not null default true,
 sort_order integer not null default 0
);
create table app.products (
 id bigint generated by default as identity primary key, slug text unique not null,
 sku text unique not null, category_id bigint references app.categories,
 name_ko text not null, name_en text not null, description_ko text not null default '',
 description_en text not null default '', price integer not null check(price>0),
 discount_price integer check(discount_price>0 and discount_price<=price),
 gender text not null default 'unisex', is_active boolean not null default false,
 is_new boolean not null default false, is_best boolean not null default false,
 created_at timestamptz not null default now()
);
create table app.product_variants (
 id uuid primary key default gen_random_uuid(), product_id bigint not null references app.products,
 sku text unique not null, color text not null, size text not null,
 swatch text, price_delta integer not null default 0,
 stock integer not null default 0 check(stock>=0), reserved integer not null default 0 check(reserved>=0 and reserved<=stock),
 active boolean not null default true, unique(product_id,color,size), unique(product_id,id)
);
create table app.product_media (
 id uuid primary key default gen_random_uuid(), product_id bigint not null references app.products,
 variant_id uuid, color text, url text not null, alt text not null default '',
 sort_order integer not null default 0, published boolean not null default true,
 foreign key(product_id,variant_id) references app.product_variants(product_id,id)
);
create table app.content (
 key text primary key, value jsonb not null, published boolean not null default false,
 starts_at timestamptz, ends_at timestamptz,
 updated_at timestamptz not null default now()
);
create table app.addresses (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references app.profiles,
 recipient text not null, phone text not null, postal_code text not null,
 address text not null, detail_address text not null default ''
);
create table app.cart_items (
 user_id uuid not null references app.profiles, variant_id uuid not null references app.product_variants,
 quantity integer not null check(quantity between 1 and 99), primary key(user_id,variant_id)
);
create table app.wishlists (
 user_id uuid not null references app.profiles, product_id bigint not null references app.products,
 primary key(user_id,product_id)
);
create table app.recently_viewed (
 user_id uuid not null references app.profiles, product_id bigint not null references app.products,
 viewed_at timestamptz not null default now(), primary key(user_id,product_id)
);
create table app.coupons (
 code text primary key, amount integer not null check(amount>0), minimum integer not null default 0,
 limit_count integer not null check(limit_count>0), used integer not null default 0,
 reserved integer not null default 0, starts_at timestamptz not null, ends_at timestamptz not null,
 check(used>=0 and reserved>=0 and used+reserved<=limit_count)
);
create table app.orders (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references app.profiles,
 order_number text unique not null, idempotency_key text not null, request_hash text not null,
 status text not null default 'pending_payment' check(status in ('pending_payment','confirming','paid','processing','shipped','delivered','canceled','expired','refund_pending','refunded')),
 subtotal integer not null check(subtotal>=0), discount integer not null check(discount>=0),
 shipping integer not null check(shipping>=0), amount integer not null check(amount>0),
 coupon_code text references app.coupons, address jsonb not null,
 expires_at timestamptz not null default now()+interval '45 minutes',
 created_at timestamptz not null default now(), unique(user_id,idempotency_key),
 check(amount=subtotal-discount+shipping)
);
create index on app.orders(user_id,created_at desc);
create table app.order_items (
 order_id uuid not null references app.orders, variant_id uuid not null references app.product_variants,
 quantity integer not null check(quantity>0), unit_price integer not null check(unit_price>0),
 snapshot jsonb not null, primary key(order_id,variant_id)
);
create table app.inventory_ledger (
 id bigint generated always as identity primary key, effect_key text unique not null,
 variant_id uuid not null references app.product_variants, quantity integer not null,
 reason text not null, created_at timestamptz not null default now()
);
create table app.payments (
 order_id uuid primary key references app.orders, payment_key text unique,
 status text not null default 'created', confirm_key uuid not null default gen_random_uuid(),
 cancel_key uuid not null default gen_random_uuid(), updated_at timestamptz not null default now()
);
create table app.webhook_events (
 id text primary key, order_number text not null, created_at timestamptz not null default now()
);
create table app.outbox (
 id uuid primary key default gen_random_uuid(), effect_key text unique not null,
 kind text not null, payload jsonb not null, attempts integer not null default 0,
 available_at timestamptz not null default now(), lease_until timestamptz,
 lease_token uuid, done_at timestamptz, last_error text, dead_at timestamptz
);
create index on app.outbox(available_at) where done_at is null and dead_at is null;
create table app.audit_logs (
 id bigint generated always as identity primary key, actor uuid references app.profiles,
 action text not null, target text not null, metadata jsonb not null default '{}',
 created_at timestamptz not null default now()
);
create table app.inquiries (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references app.profiles,
 kind text not null check(kind in ('inquiry','question','review')),
 product_id bigint references app.products, body text not null, rating integer check(rating between 1 and 5),
 published boolean not null default false, response text, created_at timestamptz not null default now()
);
create table app.privacy_requests (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references app.profiles,
 kind text not null check(kind in ('export','delete','correct')), status text not null default 'pending',
 created_at timestamptz not null default now()
);
create table app.consent_records (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references app.profiles,
 purpose text not null, version text not null, accepted boolean not null,
 created_at timestamptz not null default now()
);
create table app.rate_limits (key text primary key, count integer not null, expires_at timestamptz not null);
insert into app.content(key,value,published) values
 ('shipping','{"fee":3000,"free_threshold":70000}',true),
 ('home','{"sections":[],"announcements":[]}',true),
 ('menu','[]',true);

-- API role has no superuser, ownership or RLS bypass. Bootstrap its password out of band.
do $$ begin
 if not exists(select from pg_roles where rolname='noeul_api') then
  create role noeul_api login nosuperuser nocreatedb nocreaterole nobypassrls;
 end if;
end $$;
grant usage on schema app to noeul_api;
grant select,insert,update,delete on all tables in schema app to noeul_api;
grant usage,select on all sequences in schema app to noeul_api;
revoke update,delete on app.audit_logs,app.inventory_ledger from noeul_api;
do $$ declare t record; begin
 for t in select tablename from pg_tables where schemaname='app' loop
  execute format('alter table app.%I enable row level security',t.tablename);
  execute format('create policy backend_access on app.%I to noeul_api using (true) with check (true)',t.tablename);
 end loop;
 if exists(select from pg_roles where rolname='anon') then revoke all on schema app from anon; end if;
 if exists(select from pg_roles where rolname='authenticated') then revoke all on schema app from authenticated; end if;
end $$;
revoke all on schema app from public;
