-- 007: Fix images not loading — revert data: SVG placeholders (hsl() without commas not rendering) back to self-hosted local /products/... (free-tier, immutable cache)
-- Data URIs from 006 used hsl(140 42% 92%) space syntax not supported in some browsers + long encode bloat. Restore local reuse.
-- Per-category distinction kept via product names (each cat distinct) + variant swatch colors, not image content, until real shoots.
delete from app.product_media where product_id=20;
insert into app.product_media (product_id, url, sort_order, published, alt) values (20, '/products/men/tshirts/classic-tshirt/1.jpg', 0, true, 'Product 20 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (20, '/products/men/tshirts/classic-tshirt/2.jpg', 1, true, 'Product 20 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (20, '/products/men/tshirts/classic-tshirt/3.jpg', 2, true, 'Product 20 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (20, '/products/men/tshirts/classic-tshirt/4.jpg', 3, true, 'Product 20 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (20, '/products/men/tshirts/classic-tshirt/5.jpg', 4, true, 'Product 20 image 5') on conflict do nothing;
delete from app.product_media where product_id=21;
insert into app.product_media (product_id, url, sort_order, published, alt) values (21, '/products/men/tshirts/classic-tshirt/2.jpg', 0, true, 'Product 21 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (21, '/products/men/tshirts/classic-tshirt/3.jpg', 1, true, 'Product 21 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (21, '/products/men/tshirts/classic-tshirt/4.jpg', 2, true, 'Product 21 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (21, '/products/men/tshirts/classic-tshirt/5.jpg', 3, true, 'Product 21 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (21, '/products/women/tshirts/oversized-tshirt/1.jpg', 4, true, 'Product 21 image 5') on conflict do nothing;
delete from app.product_media where product_id=22;
insert into app.product_media (product_id, url, sort_order, published, alt) values (22, '/products/men/tshirts/classic-tshirt/3.jpg', 0, true, 'Product 22 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (22, '/products/men/tshirts/classic-tshirt/4.jpg', 1, true, 'Product 22 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (22, '/products/men/tshirts/classic-tshirt/5.jpg', 2, true, 'Product 22 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (22, '/products/women/tshirts/oversized-tshirt/1.jpg', 3, true, 'Product 22 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (22, '/products/women/tshirts/oversized-tshirt/2.jpg', 4, true, 'Product 22 image 5') on conflict do nothing;
delete from app.product_media where product_id=23;
insert into app.product_media (product_id, url, sort_order, published, alt) values (23, '/products/men/tshirts/classic-tshirt/4.jpg', 0, true, 'Product 23 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (23, '/products/men/tshirts/classic-tshirt/5.jpg', 1, true, 'Product 23 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (23, '/products/women/tshirts/oversized-tshirt/1.jpg', 2, true, 'Product 23 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (23, '/products/women/tshirts/oversized-tshirt/2.jpg', 3, true, 'Product 23 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (23, '/products/women/tshirts/oversized-tshirt/3.jpg', 4, true, 'Product 23 image 5') on conflict do nothing;
delete from app.product_media where product_id=24;
insert into app.product_media (product_id, url, sort_order, published, alt) values (24, '/products/men/tshirts/classic-tshirt/5.jpg', 0, true, 'Product 24 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (24, '/products/women/tshirts/oversized-tshirt/1.jpg', 1, true, 'Product 24 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (24, '/products/women/tshirts/oversized-tshirt/2.jpg', 2, true, 'Product 24 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (24, '/products/women/tshirts/oversized-tshirt/3.jpg', 3, true, 'Product 24 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (24, '/products/women/tshirts/oversized-tshirt/4.jpg', 4, true, 'Product 24 image 5') on conflict do nothing;
delete from app.product_media where product_id=25;
insert into app.product_media (product_id, url, sort_order, published, alt) values (25, '/products/women/tshirts/oversized-tshirt/1.jpg', 0, true, 'Product 25 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (25, '/products/women/tshirts/oversized-tshirt/2.jpg', 1, true, 'Product 25 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (25, '/products/women/tshirts/oversized-tshirt/3.jpg', 2, true, 'Product 25 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (25, '/products/women/tshirts/oversized-tshirt/4.jpg', 3, true, 'Product 25 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (25, '/products/women/tshirts/oversized-tshirt/5.jpg', 4, true, 'Product 25 image 5') on conflict do nothing;
delete from app.product_media where product_id=26;
insert into app.product_media (product_id, url, sort_order, published, alt) values (26, '/products/women/tshirts/oversized-tshirt/2.jpg', 0, true, 'Product 26 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (26, '/products/women/tshirts/oversized-tshirt/3.jpg', 1, true, 'Product 26 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (26, '/products/women/tshirts/oversized-tshirt/4.jpg', 2, true, 'Product 26 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (26, '/products/women/tshirts/oversized-tshirt/5.jpg', 3, true, 'Product 26 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (26, '/products/men/tshirts/classic-tshirt/1.jpg', 4, true, 'Product 26 image 5') on conflict do nothing;
delete from app.product_media where product_id=27;
insert into app.product_media (product_id, url, sort_order, published, alt) values (27, '/products/women/tshirts/oversized-tshirt/3.jpg', 0, true, 'Product 27 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (27, '/products/women/tshirts/oversized-tshirt/4.jpg', 1, true, 'Product 27 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (27, '/products/women/tshirts/oversized-tshirt/5.jpg', 2, true, 'Product 27 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (27, '/products/men/tshirts/classic-tshirt/1.jpg', 3, true, 'Product 27 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (27, '/products/men/tshirts/classic-tshirt/2.jpg', 4, true, 'Product 27 image 5') on conflict do nothing;
delete from app.product_media where product_id=28;
insert into app.product_media (product_id, url, sort_order, published, alt) values (28, '/products/women/tshirts/oversized-tshirt/4.jpg', 0, true, 'Product 28 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (28, '/products/women/tshirts/oversized-tshirt/5.jpg', 1, true, 'Product 28 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (28, '/products/men/tshirts/classic-tshirt/1.jpg', 2, true, 'Product 28 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (28, '/products/men/tshirts/classic-tshirt/2.jpg', 3, true, 'Product 28 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (28, '/products/men/tshirts/classic-tshirt/3.jpg', 4, true, 'Product 28 image 5') on conflict do nothing;
delete from app.product_media where product_id=29;
insert into app.product_media (product_id, url, sort_order, published, alt) values (29, '/products/women/tshirts/oversized-tshirt/5.jpg', 0, true, 'Product 29 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (29, '/products/men/tshirts/classic-tshirt/1.jpg', 1, true, 'Product 29 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (29, '/products/men/tshirts/classic-tshirt/2.jpg', 2, true, 'Product 29 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (29, '/products/men/tshirts/classic-tshirt/3.jpg', 3, true, 'Product 29 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (29, '/products/men/tshirts/classic-tshirt/4.jpg', 4, true, 'Product 29 image 5') on conflict do nothing;
delete from app.product_media where product_id=30;
insert into app.product_media (product_id, url, sort_order, published, alt) values (30, '/products/men/tshirts/classic-tshirt/1.jpg', 0, true, 'Product 30 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (30, '/products/men/tshirts/classic-tshirt/2.jpg', 1, true, 'Product 30 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (30, '/products/men/tshirts/classic-tshirt/3.jpg', 2, true, 'Product 30 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (30, '/products/men/tshirts/classic-tshirt/4.jpg', 3, true, 'Product 30 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (30, '/products/men/tshirts/classic-tshirt/5.jpg', 4, true, 'Product 30 image 5') on conflict do nothing;
delete from app.product_media where product_id=31;
insert into app.product_media (product_id, url, sort_order, published, alt) values (31, '/products/men/tshirts/classic-tshirt/2.jpg', 0, true, 'Product 31 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (31, '/products/men/tshirts/classic-tshirt/3.jpg', 1, true, 'Product 31 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (31, '/products/men/tshirts/classic-tshirt/4.jpg', 2, true, 'Product 31 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (31, '/products/men/tshirts/classic-tshirt/5.jpg', 3, true, 'Product 31 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (31, '/products/women/tshirts/oversized-tshirt/1.jpg', 4, true, 'Product 31 image 5') on conflict do nothing;
delete from app.product_media where product_id=32;
insert into app.product_media (product_id, url, sort_order, published, alt) values (32, '/products/men/tshirts/classic-tshirt/3.jpg', 0, true, 'Product 32 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (32, '/products/men/tshirts/classic-tshirt/4.jpg', 1, true, 'Product 32 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (32, '/products/men/tshirts/classic-tshirt/5.jpg', 2, true, 'Product 32 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (32, '/products/women/tshirts/oversized-tshirt/1.jpg', 3, true, 'Product 32 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (32, '/products/women/tshirts/oversized-tshirt/2.jpg', 4, true, 'Product 32 image 5') on conflict do nothing;
delete from app.product_media where product_id=33;
insert into app.product_media (product_id, url, sort_order, published, alt) values (33, '/products/men/tshirts/classic-tshirt/4.jpg', 0, true, 'Product 33 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (33, '/products/men/tshirts/classic-tshirt/5.jpg', 1, true, 'Product 33 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (33, '/products/women/tshirts/oversized-tshirt/1.jpg', 2, true, 'Product 33 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (33, '/products/women/tshirts/oversized-tshirt/2.jpg', 3, true, 'Product 33 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (33, '/products/women/tshirts/oversized-tshirt/3.jpg', 4, true, 'Product 33 image 5') on conflict do nothing;
delete from app.product_media where product_id=34;
insert into app.product_media (product_id, url, sort_order, published, alt) values (34, '/products/men/tshirts/classic-tshirt/5.jpg', 0, true, 'Product 34 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (34, '/products/women/tshirts/oversized-tshirt/1.jpg', 1, true, 'Product 34 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (34, '/products/women/tshirts/oversized-tshirt/2.jpg', 2, true, 'Product 34 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (34, '/products/women/tshirts/oversized-tshirt/3.jpg', 3, true, 'Product 34 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (34, '/products/women/tshirts/oversized-tshirt/4.jpg', 4, true, 'Product 34 image 5') on conflict do nothing;
delete from app.product_media where product_id=35;
insert into app.product_media (product_id, url, sort_order, published, alt) values (35, '/products/women/tshirts/oversized-tshirt/1.jpg', 0, true, 'Product 35 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (35, '/products/women/tshirts/oversized-tshirt/2.jpg', 1, true, 'Product 35 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (35, '/products/women/tshirts/oversized-tshirt/3.jpg', 2, true, 'Product 35 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (35, '/products/women/tshirts/oversized-tshirt/4.jpg', 3, true, 'Product 35 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (35, '/products/women/tshirts/oversized-tshirt/5.jpg', 4, true, 'Product 35 image 5') on conflict do nothing;
delete from app.product_media where product_id=36;
insert into app.product_media (product_id, url, sort_order, published, alt) values (36, '/products/women/tshirts/oversized-tshirt/2.jpg', 0, true, 'Product 36 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (36, '/products/women/tshirts/oversized-tshirt/3.jpg', 1, true, 'Product 36 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (36, '/products/women/tshirts/oversized-tshirt/4.jpg', 2, true, 'Product 36 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (36, '/products/women/tshirts/oversized-tshirt/5.jpg', 3, true, 'Product 36 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (36, '/products/men/tshirts/classic-tshirt/1.jpg', 4, true, 'Product 36 image 5') on conflict do nothing;
delete from app.product_media where product_id=37;
insert into app.product_media (product_id, url, sort_order, published, alt) values (37, '/products/women/tshirts/oversized-tshirt/3.jpg', 0, true, 'Product 37 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (37, '/products/women/tshirts/oversized-tshirt/4.jpg', 1, true, 'Product 37 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (37, '/products/women/tshirts/oversized-tshirt/5.jpg', 2, true, 'Product 37 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (37, '/products/men/tshirts/classic-tshirt/1.jpg', 3, true, 'Product 37 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (37, '/products/men/tshirts/classic-tshirt/2.jpg', 4, true, 'Product 37 image 5') on conflict do nothing;
delete from app.product_media where product_id=38;
insert into app.product_media (product_id, url, sort_order, published, alt) values (38, '/products/women/tshirts/oversized-tshirt/4.jpg', 0, true, 'Product 38 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (38, '/products/women/tshirts/oversized-tshirt/5.jpg', 1, true, 'Product 38 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (38, '/products/men/tshirts/classic-tshirt/1.jpg', 2, true, 'Product 38 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (38, '/products/men/tshirts/classic-tshirt/2.jpg', 3, true, 'Product 38 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (38, '/products/men/tshirts/classic-tshirt/3.jpg', 4, true, 'Product 38 image 5') on conflict do nothing;
delete from app.product_media where product_id=39;
insert into app.product_media (product_id, url, sort_order, published, alt) values (39, '/products/women/tshirts/oversized-tshirt/5.jpg', 0, true, 'Product 39 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (39, '/products/men/tshirts/classic-tshirt/1.jpg', 1, true, 'Product 39 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (39, '/products/men/tshirts/classic-tshirt/2.jpg', 2, true, 'Product 39 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (39, '/products/men/tshirts/classic-tshirt/3.jpg', 3, true, 'Product 39 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (39, '/products/men/tshirts/classic-tshirt/4.jpg', 4, true, 'Product 39 image 5') on conflict do nothing;
delete from app.product_media where product_id=40;
insert into app.product_media (product_id, url, sort_order, published, alt) values (40, '/products/men/tshirts/classic-tshirt/1.jpg', 0, true, 'Product 40 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (40, '/products/men/tshirts/classic-tshirt/2.jpg', 1, true, 'Product 40 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (40, '/products/men/tshirts/classic-tshirt/3.jpg', 2, true, 'Product 40 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (40, '/products/men/tshirts/classic-tshirt/4.jpg', 3, true, 'Product 40 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (40, '/products/men/tshirts/classic-tshirt/5.jpg', 4, true, 'Product 40 image 5') on conflict do nothing;
delete from app.product_media where product_id=41;
insert into app.product_media (product_id, url, sort_order, published, alt) values (41, '/products/men/tshirts/classic-tshirt/2.jpg', 0, true, 'Product 41 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (41, '/products/men/tshirts/classic-tshirt/3.jpg', 1, true, 'Product 41 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (41, '/products/men/tshirts/classic-tshirt/4.jpg', 2, true, 'Product 41 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (41, '/products/men/tshirts/classic-tshirt/5.jpg', 3, true, 'Product 41 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (41, '/products/women/tshirts/oversized-tshirt/1.jpg', 4, true, 'Product 41 image 5') on conflict do nothing;
delete from app.product_media where product_id=42;
insert into app.product_media (product_id, url, sort_order, published, alt) values (42, '/products/men/tshirts/classic-tshirt/3.jpg', 0, true, 'Product 42 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (42, '/products/men/tshirts/classic-tshirt/4.jpg', 1, true, 'Product 42 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (42, '/products/men/tshirts/classic-tshirt/5.jpg', 2, true, 'Product 42 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (42, '/products/women/tshirts/oversized-tshirt/1.jpg', 3, true, 'Product 42 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (42, '/products/women/tshirts/oversized-tshirt/2.jpg', 4, true, 'Product 42 image 5') on conflict do nothing;
delete from app.product_media where product_id=43;
insert into app.product_media (product_id, url, sort_order, published, alt) values (43, '/products/men/tshirts/classic-tshirt/4.jpg', 0, true, 'Product 43 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (43, '/products/men/tshirts/classic-tshirt/5.jpg', 1, true, 'Product 43 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (43, '/products/women/tshirts/oversized-tshirt/1.jpg', 2, true, 'Product 43 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (43, '/products/women/tshirts/oversized-tshirt/2.jpg', 3, true, 'Product 43 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (43, '/products/women/tshirts/oversized-tshirt/3.jpg', 4, true, 'Product 43 image 5') on conflict do nothing;
delete from app.product_media where product_id=44;
insert into app.product_media (product_id, url, sort_order, published, alt) values (44, '/products/men/tshirts/classic-tshirt/5.jpg', 0, true, 'Product 44 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (44, '/products/women/tshirts/oversized-tshirt/1.jpg', 1, true, 'Product 44 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (44, '/products/women/tshirts/oversized-tshirt/2.jpg', 2, true, 'Product 44 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (44, '/products/women/tshirts/oversized-tshirt/3.jpg', 3, true, 'Product 44 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (44, '/products/women/tshirts/oversized-tshirt/4.jpg', 4, true, 'Product 44 image 5') on conflict do nothing;
delete from app.product_media where product_id=45;
insert into app.product_media (product_id, url, sort_order, published, alt) values (45, '/products/women/tshirts/oversized-tshirt/1.jpg', 0, true, 'Product 45 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (45, '/products/women/tshirts/oversized-tshirt/2.jpg', 1, true, 'Product 45 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (45, '/products/women/tshirts/oversized-tshirt/3.jpg', 2, true, 'Product 45 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (45, '/products/women/tshirts/oversized-tshirt/4.jpg', 3, true, 'Product 45 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (45, '/products/women/tshirts/oversized-tshirt/5.jpg', 4, true, 'Product 45 image 5') on conflict do nothing;
delete from app.product_media where product_id=46;
insert into app.product_media (product_id, url, sort_order, published, alt) values (46, '/products/women/tshirts/oversized-tshirt/2.jpg', 0, true, 'Product 46 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (46, '/products/women/tshirts/oversized-tshirt/3.jpg', 1, true, 'Product 46 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (46, '/products/women/tshirts/oversized-tshirt/4.jpg', 2, true, 'Product 46 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (46, '/products/women/tshirts/oversized-tshirt/5.jpg', 3, true, 'Product 46 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (46, '/products/men/tshirts/classic-tshirt/1.jpg', 4, true, 'Product 46 image 5') on conflict do nothing;
delete from app.product_media where product_id=47;
insert into app.product_media (product_id, url, sort_order, published, alt) values (47, '/products/women/tshirts/oversized-tshirt/3.jpg', 0, true, 'Product 47 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (47, '/products/women/tshirts/oversized-tshirt/4.jpg', 1, true, 'Product 47 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (47, '/products/women/tshirts/oversized-tshirt/5.jpg', 2, true, 'Product 47 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (47, '/products/men/tshirts/classic-tshirt/1.jpg', 3, true, 'Product 47 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (47, '/products/men/tshirts/classic-tshirt/2.jpg', 4, true, 'Product 47 image 5') on conflict do nothing;
delete from app.product_media where product_id=48;
insert into app.product_media (product_id, url, sort_order, published, alt) values (48, '/products/women/tshirts/oversized-tshirt/4.jpg', 0, true, 'Product 48 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (48, '/products/women/tshirts/oversized-tshirt/5.jpg', 1, true, 'Product 48 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (48, '/products/men/tshirts/classic-tshirt/1.jpg', 2, true, 'Product 48 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (48, '/products/men/tshirts/classic-tshirt/2.jpg', 3, true, 'Product 48 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (48, '/products/men/tshirts/classic-tshirt/3.jpg', 4, true, 'Product 48 image 5') on conflict do nothing;
delete from app.product_media where product_id=49;
insert into app.product_media (product_id, url, sort_order, published, alt) values (49, '/products/women/tshirts/oversized-tshirt/5.jpg', 0, true, 'Product 49 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (49, '/products/men/tshirts/classic-tshirt/1.jpg', 1, true, 'Product 49 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (49, '/products/men/tshirts/classic-tshirt/2.jpg', 2, true, 'Product 49 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (49, '/products/men/tshirts/classic-tshirt/3.jpg', 3, true, 'Product 49 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (49, '/products/men/tshirts/classic-tshirt/4.jpg', 4, true, 'Product 49 image 5') on conflict do nothing;
delete from app.product_media where product_id=50;
insert into app.product_media (product_id, url, sort_order, published, alt) values (50, '/products/men/tshirts/classic-tshirt/1.jpg', 0, true, 'Product 50 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (50, '/products/men/tshirts/classic-tshirt/2.jpg', 1, true, 'Product 50 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (50, '/products/men/tshirts/classic-tshirt/3.jpg', 2, true, 'Product 50 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (50, '/products/men/tshirts/classic-tshirt/4.jpg', 3, true, 'Product 50 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (50, '/products/men/tshirts/classic-tshirt/5.jpg', 4, true, 'Product 50 image 5') on conflict do nothing;
delete from app.product_media where product_id=51;
insert into app.product_media (product_id, url, sort_order, published, alt) values (51, '/products/men/tshirts/classic-tshirt/2.jpg', 0, true, 'Product 51 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (51, '/products/men/tshirts/classic-tshirt/3.jpg', 1, true, 'Product 51 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (51, '/products/men/tshirts/classic-tshirt/4.jpg', 2, true, 'Product 51 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (51, '/products/men/tshirts/classic-tshirt/5.jpg', 3, true, 'Product 51 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (51, '/products/women/tshirts/oversized-tshirt/1.jpg', 4, true, 'Product 51 image 5') on conflict do nothing;
delete from app.product_media where product_id=52;
insert into app.product_media (product_id, url, sort_order, published, alt) values (52, '/products/men/tshirts/classic-tshirt/3.jpg', 0, true, 'Product 52 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (52, '/products/men/tshirts/classic-tshirt/4.jpg', 1, true, 'Product 52 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (52, '/products/men/tshirts/classic-tshirt/5.jpg', 2, true, 'Product 52 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (52, '/products/women/tshirts/oversized-tshirt/1.jpg', 3, true, 'Product 52 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (52, '/products/women/tshirts/oversized-tshirt/2.jpg', 4, true, 'Product 52 image 5') on conflict do nothing;
delete from app.product_media where product_id=53;
insert into app.product_media (product_id, url, sort_order, published, alt) values (53, '/products/men/tshirts/classic-tshirt/4.jpg', 0, true, 'Product 53 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (53, '/products/men/tshirts/classic-tshirt/5.jpg', 1, true, 'Product 53 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (53, '/products/women/tshirts/oversized-tshirt/1.jpg', 2, true, 'Product 53 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (53, '/products/women/tshirts/oversized-tshirt/2.jpg', 3, true, 'Product 53 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (53, '/products/women/tshirts/oversized-tshirt/3.jpg', 4, true, 'Product 53 image 5') on conflict do nothing;
delete from app.product_media where product_id=54;
insert into app.product_media (product_id, url, sort_order, published, alt) values (54, '/products/men/tshirts/classic-tshirt/5.jpg', 0, true, 'Product 54 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (54, '/products/women/tshirts/oversized-tshirt/1.jpg', 1, true, 'Product 54 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (54, '/products/women/tshirts/oversized-tshirt/2.jpg', 2, true, 'Product 54 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (54, '/products/women/tshirts/oversized-tshirt/3.jpg', 3, true, 'Product 54 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (54, '/products/women/tshirts/oversized-tshirt/4.jpg', 4, true, 'Product 54 image 5') on conflict do nothing;
delete from app.product_media where product_id=55;
insert into app.product_media (product_id, url, sort_order, published, alt) values (55, '/products/women/tshirts/oversized-tshirt/1.jpg', 0, true, 'Product 55 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (55, '/products/women/tshirts/oversized-tshirt/2.jpg', 1, true, 'Product 55 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (55, '/products/women/tshirts/oversized-tshirt/3.jpg', 2, true, 'Product 55 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (55, '/products/women/tshirts/oversized-tshirt/4.jpg', 3, true, 'Product 55 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (55, '/products/women/tshirts/oversized-tshirt/5.jpg', 4, true, 'Product 55 image 5') on conflict do nothing;
delete from app.product_media where product_id=56;
insert into app.product_media (product_id, url, sort_order, published, alt) values (56, '/products/women/tshirts/oversized-tshirt/2.jpg', 0, true, 'Product 56 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (56, '/products/women/tshirts/oversized-tshirt/3.jpg', 1, true, 'Product 56 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (56, '/products/women/tshirts/oversized-tshirt/4.jpg', 2, true, 'Product 56 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (56, '/products/women/tshirts/oversized-tshirt/5.jpg', 3, true, 'Product 56 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (56, '/products/men/tshirts/classic-tshirt/1.jpg', 4, true, 'Product 56 image 5') on conflict do nothing;
delete from app.product_media where product_id=57;
insert into app.product_media (product_id, url, sort_order, published, alt) values (57, '/products/women/tshirts/oversized-tshirt/3.jpg', 0, true, 'Product 57 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (57, '/products/women/tshirts/oversized-tshirt/4.jpg', 1, true, 'Product 57 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (57, '/products/women/tshirts/oversized-tshirt/5.jpg', 2, true, 'Product 57 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (57, '/products/men/tshirts/classic-tshirt/1.jpg', 3, true, 'Product 57 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (57, '/products/men/tshirts/classic-tshirt/2.jpg', 4, true, 'Product 57 image 5') on conflict do nothing;
delete from app.product_media where product_id=58;
insert into app.product_media (product_id, url, sort_order, published, alt) values (58, '/products/women/tshirts/oversized-tshirt/4.jpg', 0, true, 'Product 58 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (58, '/products/women/tshirts/oversized-tshirt/5.jpg', 1, true, 'Product 58 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (58, '/products/men/tshirts/classic-tshirt/1.jpg', 2, true, 'Product 58 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (58, '/products/men/tshirts/classic-tshirt/2.jpg', 3, true, 'Product 58 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (58, '/products/men/tshirts/classic-tshirt/3.jpg', 4, true, 'Product 58 image 5') on conflict do nothing;
delete from app.product_media where product_id=59;
insert into app.product_media (product_id, url, sort_order, published, alt) values (59, '/products/women/tshirts/oversized-tshirt/5.jpg', 0, true, 'Product 59 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (59, '/products/men/tshirts/classic-tshirt/1.jpg', 1, true, 'Product 59 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (59, '/products/men/tshirts/classic-tshirt/2.jpg', 2, true, 'Product 59 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (59, '/products/men/tshirts/classic-tshirt/3.jpg', 3, true, 'Product 59 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (59, '/products/men/tshirts/classic-tshirt/4.jpg', 4, true, 'Product 59 image 5') on conflict do nothing;
delete from app.product_media where product_id=60;
insert into app.product_media (product_id, url, sort_order, published, alt) values (60, '/products/men/tshirts/classic-tshirt/1.jpg', 0, true, 'Product 60 image 1') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (60, '/products/men/tshirts/classic-tshirt/2.jpg', 1, true, 'Product 60 image 2') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (60, '/products/men/tshirts/classic-tshirt/3.jpg', 2, true, 'Product 60 image 3') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (60, '/products/men/tshirts/classic-tshirt/4.jpg', 3, true, 'Product 60 image 4') on conflict do nothing;
insert into app.product_media (product_id, url, sort_order, published, alt) values (60, '/products/men/tshirts/classic-tshirt/5.jpg', 4, true, 'Product 60 image 5') on conflict do nothing;
