import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import { createClient } from '@supabase/supabase-js';
import { randomBytes, createHash } from 'node:crypto';
import { notificationService } from '../server/services/notificationService.js';

const env = process.env;
const production = env.NODE_ENV === 'production';
const required = ['APP_ORIGIN', 'SUPABASE_URL', 'SUPABASE_PUBLISHABLE_KEY', 'SESSION_KEY'];
if (production && required.some(k => !env[k])) throw new Error(`Missing production configuration: ${required.filter(k => !env[k]).join(', ')}`);
const origin = env.APP_ORIGIN || 'http://localhost:5173';
const app = express();
app.disable('x-powered-by');
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'same-site' }, contentSecurityPolicy: false }));
app.use(cors({ origin, credentials: true, methods: ['GET', 'POST', 'PATCH', 'DELETE', 'OPTIONS'], allowedHeaders: ['Content-Type', 'X-CSRF-Token', 'Idempotency-Key'] }));
app.use(rateLimit({ windowMs: 60_000, limit: 120, standardHeaders: true, legacyHeaders: false, skip: req => req.path.endsWith('/webhook') }));
const authLimiter = rateLimit({ windowMs: 15*60*1000, limit: 5, standardHeaders: true, legacyHeaders: false });
const checkoutLimiter = rateLimit({ windowMs: 15*60*1000, limit: 3, standardHeaders: true, legacyHeaders: false, skip: req => req.path.endsWith('/webhook') });
app.use(express.json({ limit: '256kb', strict: true }));
app.use((req, res, next) => { res.set('X-Content-Type-Options', 'nosniff'); res.set('Referrer-Policy', 'strict-origin-when-cross-origin'); res.set('Cache-Control', req.method === 'GET' ? 'private, max-age=0' : 'no-store'); next(); });

const serverSb = env.SUPABASE_URL && (env.SUPABASE_SECRET_KEY || env.SUPABASE_PUBLISHABLE_KEY) ? createClient(env.SUPABASE_URL, env.SUPABASE_SECRET_KEY || env.SUPABASE_PUBLISHABLE_KEY, { auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false } }) : null;
const cookieName = production ? '__Host-noeul_session' : 'noeul_session';
const sha = value => createHash('sha256').update(value).digest('hex');
const random = () => randomBytes(32).toString('base64url');
const pkceChallenge = verifier => createHash('sha256').update(verifier).digest('base64url');
const parseCookies = value => Object.fromEntries(String(value || '').split(';').map(v => v.trim().split('=').map(decodeURIComponent)).filter(v => v.length === 2));
const setCookie = (res, name, value, maxAge = 604800) => res.set('Set-Cookie', `${name}=${encodeURIComponent(value)}; Path=/; Max-Age=${maxAge}; HttpOnly; SameSite=Lax${production ? '; Secure' : ''}`);
const clearCookie = res => res.set('Set-Cookie', `${cookieName}=; Path=/; Max-Age=0; HttpOnly; SameSite=Lax${production ? '; Secure' : ''}`);
const error = (res, status, code) => res.status(status).json({ success: false, code, message: code });
const auditLog = async (req, action, details) => { try { const s = req.locals?.session; await database().from('audit_logs').insert({ actor_id: s?.user_id || null, action, target_table: details.table || null, target_id: details.id || null, before: JSON.stringify(details.before), after: JSON.stringify(details.after), ip: req.ip, user_agent: req.get('user-agent') }).maybeSingle(); } catch {} };
const requestId = req => req.headers['x-request-id'] || random().slice(2);
app.use((req, res, next) => { req.requestId = requestId(req); res.set('X-Request-ID', req.requestId); next(); });
const database = () => { if (!serverSb) throw new Error('Supabase is not configured'); return serverSb.schema('app'); };

function normalizeProduct(product) {
  if (!product) return null;
  const media = Array.isArray(product.product_media) ? product.product_media.filter(m => m.published !== false).sort((a, b) => (a.sort_order || 0) - (b.sort_order || 0)) : [];
  const variants = Array.isArray(product.product_variants) ? product.product_variants.filter(v => v.active !== false) : [];
  return { ...product, images: media.map(m => m.url), media, variants, sizes: [...new Set(variants.map(v => v.size))], colors: [...new Map(variants.map(v => [v.color, { name_ko: v.color, name_en: v.color, hex: v.swatch }])).values()], stock: variants.reduce((sum, v) => sum + Math.max(0, (v.stock || 0) - (v.reserved || 0)), 0) };
}

async function session(req, res, required = true) {
  const id = parseCookies(req.headers.cookie)?.[cookieName];
  if (!id) { if (required) error(res, 401, 'SIGN_IN_REQUIRED'); return null; }
  try {
    const { data: sessionRow, error: qErr } = await database().from('sessions').select('*').eq('id_hash', sha(id)).gt('expires_at', new Date().toISOString()).maybeSingle();
    if (qErr || !sessionRow) { if (required) error(res, 401, 'SESSION_EXPIRED'); return null; }
    const [{ data: profile }, { data: staff }] = await Promise.all([
      database().from('profiles').select('email,name,disabled').eq('id', sessionRow.user_id).maybeSingle(),
      database().from('staff_members').select('role,active').eq('user_id', sessionRow.user_id).maybeSingle(),
    ]);
    if (!profile || profile.disabled) { if (required) error(res, 401, 'SESSION_EXPIRED'); return null; }
    if (!['GET', 'HEAD', 'OPTIONS'].includes(req.method)) {
      if (req.headers.origin !== origin || req.headers['x-csrf-token'] !== sessionRow.csrf) { error(res, 403, 'CSRF_REJECTED'); return null; }
    }
    return { ...sessionRow, profiles: profile, user_id: sessionRow.user_id, role: staff?.active ? staff.role : 'customer' };
  } catch { if (required) error(res, 401, 'SESSION_EXPIRED'); return null; }
}

const authenticate = async (req, res, next) => { const s = await session(req, res, false); if (!s) return error(res, 401, 'SIGN_IN_REQUIRED'); req.locals = { session: s }; next(); };
const staff = (roles) => async (req, res, next) => { const s = req.locals?.session; if (!s || !roles.includes(s.role)) return error(res, 403, 'PERMISSION_DENIED'); if (s.aal !== 'aal2') return error(res, 403, 'MFA_REQUIRED'); next(); };

app.get('/health/live', (req, res) => res.json({ ok: true }));
app.get('/health/ready', async (req, res) => { try { await database().from('content').select('key').limit(1); res.json({ ok: true }); } catch { res.status(503).json({ ok: false }); } });

// AUTH
app.get('/api/v1/auth/google/start', authLimiter, async (req, res) => { try { const state = random(); const verifier = random(); const redirectTo = `${origin}/api/v1/auth/google/callback`; const authorize = new URL(`${env.SUPABASE_URL}/auth/v1/authorize`); authorize.searchParams.set('provider', 'google'); authorize.searchParams.set('redirect_to', redirectTo); authorize.searchParams.set('code_challenge', pkceChallenge(verifier)); authorize.searchParams.set('code_challenge_method', 'S256'); authorize.searchParams.set('access_type', 'offline'); authorize.searchParams.set('prompt', 'consent'); await database().from('oauth_states').insert({ id_hash: sha(state), verifier, expires_at: new Date(Date.now() + 600000).toISOString() }); res.set('Set-Cookie', `noeul_oauth=${encodeURIComponent(state)}; Path=/; Max-Age=600; HttpOnly; SameSite=Lax${production ? '; Secure' : ''}`); res.redirect(authorize.toString()); } catch (e) { console.error('google start failed', e); error(res, 503, 'AUTH_NOT_CONFIGURED'); } });

app.get('/api/v1/auth/google/callback', authLimiter, async (req, res) => { try { const state = parseCookies(req.headers.cookie)?.noeul_oauth; if (!state || !req.query.code) return error(res, 400, 'INVALID_CALLBACK'); const { data: row } = await database().from('oauth_states').delete().eq('id_hash', sha(state)).gt('expires_at', new Date().toISOString()).select('verifier').maybeSingle(); if (!row) return error(res, 400, 'OAUTH_STATE_EXPIRED'); const response = await fetch(`${env.SUPABASE_URL}/auth/v1/token?grant_type=pkce`, { method: 'POST', headers: { apikey: env.SUPABASE_PUBLISHABLE_KEY, 'Content-Type': 'application/json' }, body: JSON.stringify({ auth_code: req.query.code, code_verifier: row.verifier }) }); const token = await response.json(); if (!response.ok || !token.access_token || !token.user) return error(res, 401, 'GOOGLE_IDENTITY_REQUIRED'); const id = random(); const csrf = random(); await database().from('profiles').upsert({ id: token.user.id, email: token.user.email, name: token.user.user_metadata?.full_name || '' }); await database().from('sessions').insert({ id_hash: sha(id), user_id: token.user.id, encrypted_tokens: JSON.stringify(token), csrf, expires_at: new Date(Date.now() + 604800000).toISOString() }); setCookie(res, cookieName, id); res.redirect('/account'); } catch (e) { console.error('google callback failed', e); error(res, 503, 'AUTH_CALLBACK_FAILED'); } });

app.get('/api/v1/me', authenticate, async (req, res) => { const s = req.locals.session; res.set('Cache-Control', 'no-store'); res.json({ success: true, user: { id: s.user_id, uid: s.user_id, name: s.profiles.name, email: s.profiles.email, role: s.role }, csrf: s.csrf }); });
app.post('/api/v1/auth/logout', authenticate, async (req, res) => { const s = req.locals.session; if (s) await database().from('sessions').delete().eq('id_hash', s.id_hash); clearCookie(res); res.json({ success: true }); });
app.post('/api/v1/auth/logout-all', authenticate, async (req, res) => { const s = req.locals.session; if (s) await database().from('sessions').delete().eq('user_id', s.user_id); clearCookie(res); res.json({ success: true }); });

// CATALOG
app.get('/api/v1/catalog/products', async (req, res) => { try { let q = database().from('products').select('*,categories(slug),product_variants(*),product_media(*)').eq('is_active', true).order('created_at', { ascending: false }); if (req.query.search) q = q.or(`name_ko.ilike.%${req.query.search}%,name_en.ilike.%${req.query.search}%`); if (req.query.category) q = q.eq('categories.slug', req.query.category); if (req.query.gender) q = q.in('gender', [req.query.gender, 'unisex']); if (req.query.is_new === 'true' || req.query.is_new === '1') q = q.eq('is_new', true); if (req.query.is_best === 'true' || req.query.is_best === '1') q = q.eq('is_best', true); if (req.query.sort) { const sortMap = { price_asc: 'coalesce(p.discount_price,p.price)', price_desc: 'coalesce(p.discount_price,p.price) desc', popular: 'is_best desc,p.created_at desc' }; q = q.order(sortMap[req.query.sort] || 'created_at', { ascending: req.query.sort === 'price_asc' }); } const limit = Math.min(Number(req.query.limit || 24), 100); const offset = Number(req.query.offset || 0); const { data, error: e } = await q.range(offset, offset + limit - 1); if (e) throw e; res.json({ success: true, data: (data || []).map(normalizeProduct), total: (data || []).length }); } catch { error(res, 503, 'CATALOG_UNAVAILABLE'); } });

app.get('/api/v1/catalog/products/:slug', async (req, res) => { try { const { data, error: e } = await database().from('products').select('*,product_variants(*),product_media(*)').eq('slug', req.params.slug).eq('is_active', true).maybeSingle(); if (e || !data) return error(res, 404, 'PRODUCT_NOT_FOUND'); res.json({ success: true, data: normalizeProduct(data) }); } catch { error(res, 503, 'CATALOG_UNAVAILABLE'); } });
app.get('/api/v1/catalog/categories', async (req, res) => { try { const { data, error: e } = await database().from('categories').select('*').eq('is_active', true).order('sort_order'); if (e) return error(res, 503, 'CATALOG_UNAVAILABLE'); res.json({ success: true, data }); } catch { error(res, 503, 'CATALOG_UNAVAILABLE'); } });
app.get('/api/v1/content/:key', async (req, res) => { try { const key = req.params.key === 'public' ? 'shipping' : req.params.key; const { data, error: e } = await database().from('content').select('value').eq('key', key).eq('published', true).maybeSingle(); if (e || !data) return error(res, 404, 'CONTENT_NOT_FOUND'); res.json({ success: true, data: data.value }); } catch { error(res, 503, 'CONTENT_UNAVAILABLE'); } });

// CMS / SETTINGS
app.get('/api/v1/content/home', async (req, res) => { try { const { data, error: e } = await database().from('homepage_sections').select('*').eq('is_active', true).eq('is_draft', false).order('sort_order'); if (e) return error(res, 503, 'CONTENT_UNAVAILABLE'); res.json({ success: true, data: (data || []).map(s => ({ ...s, content: typeof s.content_json === 'string' ? JSON.parse(s.content_json || '{}') : s.content_json })) }); } catch { error(res, 503, 'CONTENT_UNAVAILABLE'); } });
app.get('/api/v1/content/menu', async (req, res) => { try { const { data, error: e } = await database().from('menu_items').select('*').eq('is_active', true).order('sort_order'); if (e) return error(res, 503, 'CONTENT_UNAVAILABLE'); const topLevel = (data || []).filter(i => !i.parent_id); res.json({ success: true, data: topLevel.map(item => ({ ...item, children: (data || []).filter(c => c.parent_id === item.id) })) }); } catch { error(res, 503, 'CONTENT_UNAVAILABLE'); } });
app.get('/api/v1/store/settings/public', async (req, res) => { try { const { data, error: e } = await database().from('site_settings').select('key,value'); if (e) return error(res, 503, 'SETTINGS_UNAVAILABLE'); const settings = {}; (data || []).forEach(r => { try { settings[r.key] = JSON.parse(r.value); } catch { settings[r.key] = r.value; } }); res.json({ success: true, data: { site_name: settings.site_name || 'NOEUL', currency: 'KRW', shipping_policy: settings.shipping_policy || { threshold: 70000, fee: 3000 }, free_shipping_threshold: settings.shipping_policy?.threshold || 70000, shipping_fee: settings.shipping_policy?.fee || 3000 } }); } catch { error(res, 503, 'SETTINGS_UNAVAILABLE'); } });

// CART
app.get('/api/v1/cart', authenticate, async (req, res) => { try { const { data: cart } = await database().from('carts').select('*,cart_items(*,product_variants(*))').eq('user_id', req.locals.session.user_id).eq('is_active', true).maybeSingle(); if (!cart) return res.json({ success: true, data: { items: [], subtotal: 0, shipping_fee: 0, total_amount: 0, item_count: 0 } }); const items = cart.cart_items || []; const subtotal = items.reduce((sum, i) => sum + ((i.product_variants?.discount_price || i.product_variants?.price || 0) * i.quantity), 0); const threshold = 70000; const shippingFee = subtotal >= threshold ? 0 : 3000; res.json({ success: true, data: { items, subtotal, shipping_fee: shippingFee, total_amount: subtotal + shippingFee, item_count: items.reduce((s, i) => s + i.quantity, 0) } }); } catch { error(res, 503, 'CART_UNAVAILABLE'); } });
app.post('/api/v1/cart/items', authenticate, async (req, res) => { try { const { variant_id, quantity } = req.body; const s = req.locals.session; if (!variant_id || !Number.isInteger(quantity) || quantity < 1 || quantity > 99) return error(res, 400, 'INVALID_ITEM'); const { data: pv } = await database().from('product_variants').select('*,products(*)').eq('id', variant_id).eq('active', true).maybeSingle(); if (!pv) return error(res, 404, 'VARIANT_UNAVAILABLE'); if ((pv.stock || 0) - (pv.reserved || 0) < quantity) return error(res, 409, 'INSUFFICIENT_STOCK'); const { data: cart } = await database().from('carts').select('id').eq('user_id', s.user_id).eq('is_active', true).maybeSingle(); const existing = await database().from('cart_items').select('*').eq('cart_id', cart?.id || '').eq('variant_id', variant_id).maybeSingle(); if (existing.length > 0) { await database().from('cart_items').update({ quantity: existing[0].quantity + quantity }).eq('id', existing[0].id); } else { await database().from('cart_items').insert({ cart_id: cart?.id, variant_id, quantity }); } res.json({ success: true }); } catch { error(res, 503, 'CART_UNAVAILABLE'); } });
app.delete('/api/v1/cart/items/:id', authenticate, async (req, res) => { try { await database().from('cart_items').delete().eq('id', req.params.id); res.json({ success: true }); } catch { error(res, 503, 'CART_UNAVAILABLE'); } });

// WISHLIST
app.get('/api/v1/wishlist', authenticate, async (req, res) => { try { const { data, error: e } = await database().from('wishlists').select('*,products(*)').eq('user_id', req.locals.session.user_id).order('created_at', { ascending: false }); if (e) throw e; res.json({ success: true, data: (data || []).map(w => w.products) }); } catch { error(res, 503, 'WISHLIST_UNAVAILABLE'); } });
app.post('/api/v1/wishlist/toggle', authenticate, async (req, res) => { try { const { product_id } = req.body; const s = req.locals.session; if (!product_id) return error(res, 400, 'PRODUCT_ID_REQUIRED'); const existing = await database().from('wishlists').select('*').eq('user_id', s.user_id).eq('product_id', product_id).maybeSingle(); if (existing.length > 0) { await database().from('wishlists').delete().eq('id', existing[0].id); res.json({ success: true, is_wishlisted: false }); } else { await database().from('wishlists').insert({ user_id: s.user_id, product_id }); res.json({ success: true, is_wishlisted: true }); } } catch { error(res, 503, 'WISHLIST_UNAVAILABLE'); } });

// REVIEWS
app.get('/api/v1/products/:id/reviews', async (req, res) => { try { const { data, error: e } = await database().from('reviews').select('*').eq('product_id', req.params.id).eq('is_approved', true).order('created_at', { ascending: false }); if (e) throw e; res.json({ success: true, data: data || [] }); } catch { error(res, 503, 'REVIEWS_UNAVAILABLE'); } });

// ORDERS
app.post('/api/v1/checkout/quote', authenticate, async (req, res) => { try { const { items, coupon_code } = req.body; if (!items || !Array.isArray(items) || items.length === 0) return error(res, 400, 'INVALID_ITEMS'); const ids = items.map(i => i.variant_id); const { data: variants } = await database().from('product_variants').select('*,products(*)').in('id', ids); if (!variants || variants.length !== items.length) return error(res, 404, 'VARIANT_UNAVAILABLE'); let subtotal = 0; const lines = []; for (const item of items) { const v = variants.find(x => x.id === item.variant_id); if (!v || !v.active) return error(res, 400, 'VARIANT_UNAVAILABLE'); if ((v.stock || 0) - (v.reserved || 0) < item.quantity) return error(res, 409, 'INSUFFICIENT_STOCK'); const unit = Math.max(1, (v.discount_price || v.price) + (v.price_delta || 0)); subtotal += unit * item.quantity; lines.push({ variant_id: v.id, quantity: item.quantity, unit_price: unit }); } let discount = 0; if (coupon_code) { const { data: coupon } = await database().from('coupons').eq('code', coupon_code.toUpperCase().trim()).eq('is_active', true).maybeSingle(); if (coupon && coupon.start_date <= new Date().toISOString().split('T')[0] && coupon.end_date >= new Date().toISOString().split('T')[0] && coupon.used + (coupon.reserved || 0) < coupon.limit_count && subtotal >= coupon.minimum) { discount = Math.min(subtotal, coupon.discount_type === 'percentage' ? Math.round(subtotal * coupon.discount_value / 100) : coupon.discount_value); } } const shippingFee = subtotal - discount >= 70000 ? 0 : 3000; res.json({ success: true, data: { subtotal, discount, shipping: shippingFee, amount: subtotal - discount + shippingFee, items: lines, coupon: discount > 0 ? 'applied' : null } }); } catch { error(res, 503, 'QUOTE_UNAVAILABLE'); } });

app.post('/api/v1/orders', authenticate, checkoutLimiter, async (req, res) => { try { const s = req.locals.session; const idempotencyKey = String(req.get('Idempotency-Key') || ''); if (!/^[A-Za-z0-9._:-]{8,200}$/.test(idempotencyKey)) return error(res, 400, 'IDEMPOTENCY_KEY_REQUIRED'); const requestHash = createHash('sha256').update(JSON.stringify(req.body)).digest('hex'); const { data: existing } = await database().from('orders').select('*').eq('user_id', s.user_id).eq('idempotency_key', idempotencyKey).maybeSingle(); if (existing && existing.request_hash === requestHash) return res.json({ success: true, data: existing, duplicated: true }); const number = `NE${Date.now().toString(36).toUpperCase()}${random().slice(2, 8).toUpperCase()}`; const { data: order, error: oErr } = await database().from('orders').insert({ user_id: s.user_id, order_number: number, subtotal: req.body.subtotal || 0, discount_amount: req.body.discount || 0, shipping_fee: req.body.shipping || 0, total_amount: req.body.amount || 0, payment_method: 'toss_card', payment_status: 'pending_payment', order_status: 'pending_payment', idempotency_key: idempotencyKey, request_hash: requestHash }).select().maybeSingle(); if (oErr) throw oErr; await database().from('outbox_events').insert({ effect_key: `order:${order.id}`, kind: 'ORDER_CREATED', payload: JSON.stringify({ order_id: order.id }) }); res.status(201).json({ success: true, data: order }); } catch { error(res, 503, 'ORDER_UNAVAILABLE'); } });
app.get('/api/v1/orders', authenticate, async (req, res) => { try { const { data, error: e } = await database().from('orders').select('*').eq('user_id', req.locals.session.user_id).order('created_at', { ascending: false }).limit(100); if (e) throw e; res.json({ success: true, data: data || [] }); } catch { error(res, 503, 'ORDERS_UNAVAILABLE'); } });
app.get('/api/v1/orders/:publicId', authenticate, async (req, res) => { try { const { data: order } = await database().from('orders').select('*').eq('order_number', req.params.publicId).eq('user_id', req.locals.session.user_id).maybeSingle(); if (!order) return error(res, 404, 'ORDER_NOT_FOUND'); const items = await database().from('order_items').select('*').eq('order_id', order.id); res.json({ success: true, data: { ...order, items } }); } catch { error(res, 503, 'ORDERS_UNAVAILABLE'); } });

// Cancel order
app.post('/api/v1/orders/:publicId/cancel', authenticate, async (req, res) => { try { const s = req.locals.session; const { data: order } = await database().from('orders').select('*').eq('order_number', req.params.publicId).eq('user_id', s.user_id).maybeSingle(); if (!order) return error(res, 404, 'ORDER_NOT_FOUND'); if (!['pending_payment', 'paid'].includes(order.order_status)) return error(res, 409, 'ORDER_NOT_CANCELLABLE'); await database().from('orders').update({ order_status: 'canceled' }).eq('id', order.id); const { data: items } = await database().from('order_items').select('*').eq('order_id', order.id); for (const item of items) { const { data: pv } = await database().from('product_variants').select('reserved').eq('id', item.variant_id).single(); if (pv && pv.reserved >= item.quantity) { await database().from('product_variants').update({ reserved: pv.reserved - item.quantity }).eq('id', item.variant_id); } } res.json({ success: true, data: order }); } catch { error(res, 503, 'ORDERS_UNAVAILABLE'); } });

// TOSS PAYMENTS
app.post('/api/v1/payments/toss/prepare', authenticate, checkoutLimiter, authenticate, async (req, res) => { try { if (env.PAYMENTS_ENABLED === 'true') return error(res, 503, 'PAYMENTS_DISABLED'); const s = req.locals.session; const { orderId } = req.body; const { data: order } = await database().from('orders').select('*').eq('order_number', orderId).eq('user_id', s.user_id).maybeSingle(); if (!order) return error(res, 404, 'ORDER_NOT_FOUND'); res.json({ success: true, data: { orderId: order.order_number, amount: order.total_amount, clientKey: env.TOSS_CLIENT_KEY || '' } }); } catch { error(res, 503, 'PAYMENTS_UNAVAILABLE'); } });
app.post('/api/v1/payments/toss/confirm', authenticate, checkoutLimiter, authenticate, async (req, res) => { try { if (env.PAYMENTS_ENABLED === 'true') return error(res, 503, 'PAYMENTS_DISABLED'); const { paymentKey, orderId, amount } = req.body; const s = req.locals.session; const { data: order } = await database().from('orders').select('*').eq('order_number', orderId).eq('user_id', s.user_id).maybeSingle(); if (!order) return error(res, 404, 'ORDER_NOT_FOUND'); if (order.amount !== amount) return error(res, 400, 'AMOUNT_MISMATCH'); if (!['pending_payment', 'confirming'].includes(order.order_status)) return error(res, 409, 'ORDER_STATE_INVALID'); await database().from('orders').update({ status: 'confirming' }).eq('id', order.id); try { const tossRes = await fetch(`https://api.tosspayments.com/v1/payments/confirm`, { method: 'POST', headers: { Authorization: `Basic ${Buffer.from(`${env.TOSS_SECRET_KEY}:`).toString('base64')}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ paymentKey, orderId, amount }) }); const payment = await tossRes.json(); if (!tossRes.ok) throw payment; await database().from('orders').update({ payment_status: 'paid', order_status: 'paid' }).eq('id', order.id); await database().from('outbox_events').insert({ effect_key: `payment:${order.id}`, kind: 'PAYMENT_CONFIRMED', payload: JSON.stringify({ order_id: order.id, status: 'paid' }) }); res.json({ success: true, data: { orderId: order.order_number, status: 'paid' } }); } catch (err) { await database().from('orders').update({ order_status: 'pending_payment' }).eq('id', order.id); throw err; } } catch { error(res, 503, 'PAYMENTS_UNAVAILABLE'); } });
app.post('/api/v1/payments/toss/webhook', async (req, res) => { try { res.sendStatus(200); const body = req.body; if (!body.orderId) return; const id = String(req.get('tosspayments-webhook-transmission-id') || `${body.orderId}:${body.status}`); await database().from('webhook_events').insert({ id, order_number: body.orderId, status: body.status }).maybeSingle(); } catch { /* eslint-disable-line no-empty */ } });
app.post('/api/v1/admin/payments/:id/refunds', staff(['super_admin', 'admin', 'order_manager']), async (req, res) => { try { const { data: payment } = await database().from('payments').select('*,orders(*)').eq('order_id', req.params.id).maybeSingle(); if (!payment?.payment_key) return error(res, 404, 'PAYMENT_NOT_FOUND'); try { const tossRes = await fetch(`https://api.tosspayments.com/v1/payments/${payment.payment_key}/cancel`, { method: 'POST', headers: { Authorization: `Basic ${Buffer.from(`${env.TOSS_SECRET_KEY}:`).toString('base64')}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ cancelReason: req.body.reason }) }); const result = await tossRes.json(); await database().from('payments').update({ status: 'refunded' }).eq('order_id', payment.order_id); await database().from('orders').update({ order_status: 'refunded' }).eq('id', payment.order_id); res.json({ success: true, data: result }); } catch (err) { error(res, 500, 'REFUND_FAILED'); } } catch { error(res, 503, 'PAYMENTS_UNAVAILABLE'); } });


// SHIPMENT / TRACKING
app.post('/api/v1/orders/:publicId/shipments', authenticate, staff(['super_admin','admin','order_manager']), async (req, res) => { try { const s = req.locals.session; const { data: order } = await database().from('orders').select('*').eq('order_number', req.params.publicId).eq('user_id', s.user_id).maybeSingle(); if (!order) return error(res, 404, 'ORDER_NOT_FOUND'); const { data: shipment } = await database().from('shipments').insert({ order_id: order.id, courier_name: req.body.courier, tracking_number: req.body.tracking_number, status: 'dispatched' }).select().maybeSingle(); await database().from('order_status_history').insert({ order_id: order.id, status: 'shipped', note: 'Shipment dispatched', actor_id: s.user_id }); await notificationService.sendShippingUpdate(order); res.json({ success: true, data: shipment }); } catch { error(res, 503, 'SHIPMENT_UNAVAILABLE'); } });
app.get('/api/v1/orders/:publicId/tracking', authenticate, async (req, res) => { try { const { data: order } = await database().from('orders').select('*').eq('order_number', req.params.publicId).eq('user_id', req.locals.session.user_id).maybeSingle(); if (!order) return error(res, 404, 'ORDER_NOT_FOUND'); const { data: events } = await database().from('order_status_history').select('*').eq('order_id', order.id).order('created_at', { ascending: false }); res.json({ success: true, data: { order, events } }); } catch { error(res, 503, 'TRACKING_UNAVAILABLE'); } });
app.post('/api/v1/orders/:publicId/cancel', authenticate, async (req, res) => { try { const s = req.locals.session; const { data: order } = await database().from('orders').select('*').eq('order_number', req.params.publicId).eq('user_id', s.user_id).maybeSingle(); if (!order) return error(res, 404, 'ORDER_NOT_FOUND'); if (!['pending_payment','paid'].includes(order.order_status)) return error(res, 409, 'ORDER_NOT_CANCELLABLE'); await database().from('orders').update({ order_status: 'canceled' }).eq('id', order.id); const { data: items } = await database().from('order_items').select('*').eq('order_id', order.id); for (const item of items) { const { data: pv } = await database().from('product_variants').select('reserved').eq('id', item.variant_id).single(); if (pv && pv.reserved >= item.quantity) { await database().from('product_variants').update({ reserved: pv.reserved - item.quantity }).eq('id', item.variant_id); } } await notificationService.sendCancellationNotification(order); res.json({ success: true, data: order }); } catch { error(res, 503, 'ORDERS_UNAVAILABLE'); } });

// REVIEW MODERATION
app.post('/api/v1/reviews/:id/moderate', authenticate, staff(['super_admin','admin']), async (req, res) => { try { const { data: review } = await database().from('reviews').select('*').eq('id', req.params.id).maybeSingle(); if (!review) return error(res, 404, 'REVIEW_NOT_FOUND'); const { is_approved } = req.body; await database().from('reviews').update({ is_approved, moderated_by: req.locals.session.user_id, moderated_at: new Date().toISOString() }).eq('id', req.params.id); await auditLog(req, 'REVIEW_MODERATE', { table: 'reviews', id: req.params.id }); res.json({ success: true }); } catch { error(res, 503, 'MODERATION_UNAVAILABLE'); } });

// PRIVACY REQUESTS
app.post('/api/v1/me/privacy-request', authenticate, async (req, res) => { try { const s = req.locals.session; const { data: privacy } = await database().from('privacy_requests').insert({ user_id: s.user_id, type: req.body.type, status: 'pending', created_at: new Date().toISOString() }).select().maybeSingle(); await notificationService.sendInquiryResponse({ id: privacy.id, customer_email: s.profiles.email, category: 'privacy', response: 'Your request has been received and is being processed.' }); res.json({ success: true, data: privacy }); } catch { error(res, 503, 'PRIVACY_UNAVAILABLE'); } });
app.get('/api/v1/admin/privacy-requests', authenticate, staff(['super_admin','admin']), async (req, res) => { try { const { data } = await database().from('privacy_requests').select('*').order('created_at', { ascending: false }).limit(100); res.json({ success: true, data: data || [] }); } catch { error(res, 503, 'PRIVACY_UNAVAILABLE'); } });

// AUDIT LOGS
app.get('/api/v1/admin/audit-logs', authenticate, staff(['super_admin','admin']), async (req, res) => { try { const { data } = await database().from('audit_logs').select('*').order('created_at', { ascending: false }).limit(200); res.json({ success: true, data: data || [] }); } catch { error(res, 503, 'AUDIT_UNAVAILABLE'); } });

// ERROR HANDLER
app.use((err, req, res, next) => { /* eslint-disable-line no-unused-vars */ console.error(err); if (!res.headersSent) error(res, 500, 'INTERNAL_ERROR'); });

const port = Number(env.PORT || 5001);
export default app;
export const router = app;
if (process.argv[1] === new URL(import.meta.url).pathname) { app.listen(port, () => console.log(`NOEUL production API listening on ${port}`)); }
