import { Router } from 'express';import { z } from 'zod';import { type Database,sql } from './db.js';import { ensure } from './security.js';import type { Config } from './config.js';
const confirmSchema=z.object({paymentKey:z.string().min(1).max(200),orderId:z.string().min(6).max(64),amount:z.number().int().positive()});
const toss=(c:Config)=>'https://api.tosspayments.com/v1/payments';
async function callToss(c:Config,path:string,body?:any,method='GET',idem?:string){const h:any={Authorization:`Basic ${Buffer.from(`${c.TOSS_SECRET_KEY}:`).toString('base64')}`,'Content-Type':'application/json'};if(idem)h['Idempotency-Key']=idem;const r=await fetch(`${toss(c)}${path}`,{method,headers:h,body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.message||'Toss request failed'),{status:r.status,data});return data;}
export function payments(db:Database,auth:any,c:Config){const r=Router();
 r.use(auth.authenticate);r.post('/payments/toss/prepare',async(req,res,next)=>{try{ensure(c.PAYMENTS_ENABLED==='true',503,'PAYMENTS_DISABLED');const s=res.locals.session;const [o]=await db.rows<any>(sql`select o.*,p.confirm_key from app.orders o join app.payments p on p.order_id=o.id where o.order_number=${req.body.orderId} and o.user_id=${s.user_id}`);ensure(o,404,'ORDER_NOT_FOUND');res.json({success:true,data:{orderId:o.order_number,amount:o.amount,clientKey:c.TOSS_CLIENT_KEY}});}catch(e){next(e);}});
 r.post('/payments/toss/confirm',async(req,res,next)=>{try{ensure(c.PAYMENTS_ENABLED==='true',503,'PAYMENTS_DISABLED');const input=confirmSchema.parse(req.body),s=res.locals.session;const [o]=await db.rows<any>(sql`select o.*,p.confirm_key,p.status as payment_status from app.orders o join app.payments p on p.order_id=o.id where o.order_number=${input.orderId} and o.user_id=${s.user_id} for update`);ensure(o,404,'ORDER_NOT_FOUND');ensure(o.amount===input.amount,400,'AMOUNT_MISMATCH');ensure(['pending_payment','confirming'].includes(o.status),409,'ORDER_STATE_INVALID');await db.rows(sql`update app.orders set status='confirming' where id=${o.id}`);const payment=await callToss(c,`/confirm`,{paymentKey:input.paymentKey,orderId:input.orderId,amount:input.amount},'POST',String(o.confirm_key));ensure(payment.method==='카드'||payment.method==='CARD',400,'CARD_ONLY');await db.transaction(async tx=>{await tx.rows(sql`update app.payments set payment_key=${input.paymentKey},status='paid',updated_at=now() where order_id=${o.id}`);await tx.rows(sql`update app.orders set status='paid' where id=${o.id}`);const lines=await tx.rows<any>(sql`select * from app.order_items where order_id=${o.id}`);for(const l of lines){await tx.rows(sql`update app.product_variants set stock=stock-l.quantity,reserved=reserved-l.quantity where id=${l.variant_id} and reserved>=${l.quantity}`);}});res.json({success:true,data:{orderId:o.order_number,status:'paid'}});}catch(e){next(e);}});
 r.post('/payments/toss/webhook',async(req,res)=>{const body=req.body||{};res.sendStatus(200);try{if(!body.orderId||!body.status)return;const [o]=await db.rows<any>(sql`select id,order_number from app.orders where order_number=${body.orderId}`);if(!o)return;const id=String(req.get('tosspayments-webhook-transmission-id')||`${body.orderId}:${body.status}:${body.createdAt||''}`);const inserted=await db.rows(sql`insert into app.webhook_events(id,order_number) values(${id},${body.orderId}) on conflict do nothing returning id`);if(!inserted.length)return;const p=await callToss(c,`/${encodeURIComponent(body.paymentKey||body.transactionKey||'')}`);await db.rows(sql`update app.payments set status=${String(p.status||'').toLowerCase()},updated_at=now() where order_id=${o.id}`);}catch(e){console.error('Toss webhook reconciliation failed',e);}});
 r.post('/admin/payments/:id/refunds',auth.staff(['super_admin','admin','order_manager']),async(req,res,next)=>{try{const [p]=await db.rows<any>(sql`select p.*,o.order_number,o.user_id from app.payments p join app.orders o on o.id=p.order_id where p.order_id=${req.params.id}`);ensure(p?.payment_key,404,'PAYMENT_NOT_FOUND');const reason=z.string().min(1).max(200).parse(req.body.reason);const data=await callToss(c,`/${p.payment_key}/cancel`,{cancelReason:reason},'POST',String(p.cancel_key));await db.rows(sql`update app.payments set status='refunded',updated_at=now() where order_id=${p.order_id}`);await db.rows(sql`update app.orders set status='refunded' where id=${p.order_id}`);res.json({success:true,data});}catch(e){next(e);}});return r;}
